
package ipc1.f._1s2026.views;

import ipc1.f._1s2026.controllers.AgregarController;
import ipc1.f._1s2026.models.AgregarModel;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fofo_
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    
    AgregarController verController = new AgregarController();
    
    VistaDatosE vDatosE;
    
    VistaAgregar vAgregar;
    
    VistaVenta vistaVenta;
    
    public void mostrarResultados(AgregarModel[] resultados){

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        for(AgregarModel p : resultados){

            if(p != null){

                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNombre(),
                    p.getCategoria(),
                    p.getPrecio(),
                    p.getCantidad()
                });

            }

        }

    }
    
    public void actualizarTabla(AgregarModel[] productos){

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0); // limpia la tabla

        for(AgregarModel p : productos){

            if(p != null){

                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNombre(),
                    p.getCategoria(),
                    p.getPrecio(),
                    p.getCantidad()
                });

            }

        }

    }
    
    public VistaPrincipal() {
        initComponents();
        
        DefaultTableModel modelo = new DefaultTableModel();
    
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
    
        tablaProductos.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btmAgregar = new javax.swing.JButton();
        btmBuscar = new javax.swing.JButton();
        btmEliminar = new javax.swing.JButton();
        btmRegistrar = new javax.swing.JButton();
        btmGenerarStock = new javax.swing.JButton();
        btmDatosES = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();
        btmGenerarVentas = new javax.swing.JButton();
        cmbSelector = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        txtActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Menu Principal");

        btmAgregar.setText("Agregar Producto");
        btmAgregar.addActionListener(this::btmAgregarActionPerformed);

        btmBuscar.setText("Buscar Producto");
        btmBuscar.addActionListener(this::btmBuscarActionPerformed);

        btmEliminar.setText("Eliminar Producto");
        btmEliminar.addActionListener(this::btmEliminarActionPerformed);

        btmRegistrar.setText("Registrar Venta");
        btmRegistrar.addActionListener(this::btmRegistrarActionPerformed);

        btmGenerarStock.setText("Generar Reporte Stock");
        btmGenerarStock.addActionListener(this::btmGenerarStockActionPerformed);

        btmDatosES.setText("Datos Estudiante");
        btmDatosES.addActionListener(this::btmDatosESActionPerformed);

        btmSalir.setBackground(new java.awt.Color(255, 0, 0));
        btmSalir.setForeground(new java.awt.Color(255, 255, 255));
        btmSalir.setText("SALIR");
        btmSalir.addActionListener(this::btmSalirActionPerformed);

        btmGenerarVentas.setText("Generar Reporte Ventas");
        btmGenerarVentas.addActionListener(this::btmGenerarVentasActionPerformed);

        cmbSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Categoria" }));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Categoria", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        txtActualizar.setText("Actualizar Tabla");
        txtActualizar.addActionListener(this::txtActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btmBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btmAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btmSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btmDatosES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btmGenerarVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btmGenerarStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btmEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btmRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btmAgregar, btmBuscar, btmDatosES, btmEliminar, btmGenerarStock, btmGenerarVentas, btmRegistrar, btmSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmBuscar)
                    .addComponent(cmbSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btmAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btmRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmGenerarStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmGenerarVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmDatosES, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmSalir)))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btmAgregar, btmBuscar, btmDatosES, btmEliminar, btmGenerarStock, btmGenerarVentas, btmRegistrar, btmSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgregarActionPerformed
        this.setVisible(false);
        
        vAgregar = new VistaAgregar(this);
        vAgregar.setVisible(true);
   
    }//GEN-LAST:event_btmAgregarActionPerformed

    private void btmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEliminarActionPerformed
        
        
        VistaBorrar eliminar = new VistaBorrar(this);
        eliminar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmEliminarActionPerformed

    private void btmDatosESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDatosESActionPerformed
        
        vDatosE = new VistaDatosE(this);
        vDatosE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmDatosESActionPerformed

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btmSalirActionPerformed

    private void btmGenerarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmGenerarStockActionPerformed
        try {
            verController.generarHTML();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btmGenerarStockActionPerformed

    private void btmGenerarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmGenerarVentasActionPerformed
        try{
        verController.generarReporteVentas();
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btmGenerarVentasActionPerformed

    private void btmBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBuscarActionPerformed
        String criterio = cmbSelector.getSelectedItem().toString();
        String valor = txtBuscar.getText();

        AgregarModel[] resultados = verController.buscarProducto(criterio, valor);

        mostrarResultados(resultados);
    }//GEN-LAST:event_btmBuscarActionPerformed

    private void btmRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegistrarActionPerformed
        this.setVisible(false);
        vistaVenta = new VistaVenta(this, verController);
        vistaVenta.setVisible(true);
    }//GEN-LAST:event_btmRegistrarActionPerformed

    private void txtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarActionPerformed
        
        actualizarTabla(verController.obtenerProductos());
    }//GEN-LAST:event_txtActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAgregar;
    private javax.swing.JButton btmBuscar;
    private javax.swing.JButton btmDatosES;
    private javax.swing.JButton btmEliminar;
    private javax.swing.JButton btmGenerarStock;
    private javax.swing.JButton btmGenerarVentas;
    private javax.swing.JButton btmRegistrar;
    private javax.swing.JButton btmSalir;
    private javax.swing.JComboBox<String> cmbSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JButton txtActualizar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

