
package ipc1.f._1s2026.views;

import ipc1.f._1s2026.controllers.AgregarController;
import javax.swing.JOptionPane;

/**
 *
 * @author fofo_
 */
public class VistaBorrar extends javax.swing.JFrame {
    
    AgregarController controller = new AgregarController();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaBorrar.class.getName());

    /**
     * Creates new form VistaBorrar
     */
    public VistaBorrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodeErase = new javax.swing.JTextField();
        btmBorrar = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el código del producto a eliminar:");

        txtCodeErase.addActionListener(this::txtCodeEraseActionPerformed);

        btmBorrar.setBackground(new java.awt.Color(255, 51, 51));
        btmBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btmBorrar.setText("Borrar");
        btmBorrar.addActionListener(this::btmBorrarActionPerformed);

        btmSalir.setText("Salir");
        btmSalir.addActionListener(this::btmSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmSalir)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodeErase, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btmBorrar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeErase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmBorrar))
                .addGap(39, 39, 39)
                .addComponent(btmSalir)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeEraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeEraseActionPerformed

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btmSalirActionPerformed

    private void btmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBorrarActionPerformed
        int codigo = Integer.parseInt(txtCodeErase.getText());

        //controller.eliminarProducto(codigo);
        
        boolean eliminado = controller.eliminarProducto(codigo);

        if(eliminado){
            JOptionPane.showMessageDialog(null,"Producto eliminado");
        }else{
            JOptionPane.showMessageDialog(null,"Producto no encontrado");
            }
    }//GEN-LAST:event_btmBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaBorrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBorrar;
    private javax.swing.JButton btmSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCodeErase;
    // End of variables declaration//GEN-END:variables
}
