
package ipc1.f._1s2026.views;

import ipc1.f._1s2026.controllers.AgregarController;
import javax.swing.JOptionPane;

/**
 *
 * @author fofo_
 */
public class VistaBorrar extends javax.swing.JFrame {
    
    private final VistaPrincipal vistaPrincipal;
    private final AgregarController controller = new AgregarController();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaBorrar.class.getName());
    
    public VistaBorrar(VistaPrincipal vp) {
        
        initComponents();
        this.vistaPrincipal = vp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodeErase = new javax.swing.JTextField();
        btmBorrar = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el código del producto a eliminar:");

        txtCodeErase.addActionListener(this::txtCodeEraseActionPerformed);

        btmBorrar.setBackground(new java.awt.Color(255, 51, 51));
        btmBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btmBorrar.setText("Borrar");
        btmBorrar.addActionListener(this::btmBorrarActionPerformed);

        btmSalir.setText("Salir");
        btmSalir.addActionListener(this::btmSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmSalir)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodeErase, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btmBorrar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeErase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmBorrar))
                .addGap(39, 39, 39)
                .addComponent(btmSalir)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeEraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeEraseActionPerformed

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
        this.setVisible(false);
        vistaPrincipal.setVisible(true);
    }//GEN-LAST:event_btmSalirActionPerformed

    private void btmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBorrarActionPerformed

      String valor = txtCodeErase.getText().trim();

        // Validamos que el campo no esté vacío
        if(valor.isEmpty()){
            JOptionPane.showMessageDialog(
                null,
                "Debe ingresar un código para borrar.",
                "Error",
                JOptionPane.WARNING_MESSAGE
            );
            txtCodeErase.requestFocus();
            return;
        }

        int codigo;
        try {
            codigo = Integer.parseInt(valor); // Convertimos a entero
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "El código debe ser un número válido.",
                "Error",
                JOptionPane.WARNING_MESSAGE
            );
            txtCodeErase.requestFocus();
            return;
        }

        // Confirmación antes de borrar
        int opcion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro que desea eliminar el producto con código " + codigo + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if(opcion == JOptionPane.YES_OPTION){
            boolean eliminado = controller.eliminarProducto(codigo);
            if(eliminado){
                JOptionPane.showMessageDialog(
                    null,
                    "Producto eliminado exitosamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Producto no encontrado.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } else {
            // Si el usuario cancela
            JOptionPane.showMessageDialog(
                null,
                "Eliminación cancelada.",
                "Cancelado",
                JOptionPane.INFORMATION_MESSAGE
            );
        }

        txtCodeErase.setText("");
        txtCodeErase.requestFocus();      
            
    }//GEN-LAST:event_btmBorrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBorrar;
    private javax.swing.JButton btmSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCodeErase;
    // End of variables declaration//GEN-END:variables
}
