/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1.f._1s2026.views;

import ipc1.f._1s2026.controllers.AgregarController;

/**
 *
 * @author fofo_
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    
    VistaAgregar vAgregar = new VistaAgregar();
    
    AgregarController verController = new AgregarController();
    
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btmAgregar = new javax.swing.JButton();
        btmBuscar = new javax.swing.JButton();
        btmEliminar = new javax.swing.JButton();
        btmRegistrar = new javax.swing.JButton();
        btmGenerarR = new javax.swing.JButton();
        btmDatosES = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();
        btmVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Principal");

        btmAgregar.setText("Agregar Producto");
        btmAgregar.addActionListener(this::btmAgregarActionPerformed);

        btmBuscar.setText("Buscar Producto");

        btmEliminar.setText("Eliminar Producto");
        btmEliminar.addActionListener(this::btmEliminarActionPerformed);

        btmRegistrar.setText("Registrar Venta");

        btmGenerarR.setText("Generar Reporte");

        btmDatosES.setText("Ver Datos Estudiante");

        btmSalir.setText("SALIR");

        btmVer.setText("VER");
        btmVer.addActionListener(this::btmVerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btmSalir)
                            .addComponent(btmDatosES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmGenerarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addComponent(btmVer)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmAgregar)
                    .addComponent(btmVer))
                .addGap(18, 18, 18)
                .addComponent(btmBuscar)
                .addGap(18, 18, 18)
                .addComponent(btmEliminar)
                .addGap(18, 18, 18)
                .addComponent(btmRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btmGenerarR)
                .addGap(18, 18, 18)
                .addComponent(btmDatosES)
                .addGap(18, 18, 18)
                .addComponent(btmSalir)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgregarActionPerformed
        
        vAgregar.setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_btmAgregarActionPerformed

    private void btmEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmEliminarActionPerformed

    private void btmVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmVerActionPerformed
        //Para ver matriz 
        verController.verAgregar();
    }//GEN-LAST:event_btmVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAgregar;
    private javax.swing.JButton btmBuscar;
    private javax.swing.JButton btmDatosES;
    private javax.swing.JButton btmEliminar;
    private javax.swing.JButton btmGenerarR;
    private javax.swing.JButton btmRegistrar;
    private javax.swing.JButton btmSalir;
    private javax.swing.JButton btmVer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
